services:
    dmzx.copyright.listener:
        class: dmzx\copyright\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
